from njembe.config import EXPORT_FOLDER

import os

# Utils functions

def generate_docfile(documentation, steps, bash=False):
	"""
		Utility function used to write an executable bash script,
		which can be exported and run on every unix-based os.
	"""

	env = "#!/usr/bin/env bash\n"

	header = \
	"""
	# Autogenerated by njembe (0.0.1) https://github.com/st9-8/njembe
	#
	# DO NOT EDIT UNLESS YOU ARE THAT YOU KNOW WHAT YOU ARE DOING
	#
	# MIT 2021
	"""
	c = '# ' if bash else ''		# Comment flag

	if bash:
		filename = os.path.join(EXPORT_FOLDER, 'generated_scripts', f'scriptdoc_{documentation.id}.sh')
	else:
		filename = os.path.join(EXPORT_FOLDER, 'generated_docs', f'doc_{documentation.id}.nj')

	doc = []

	if bash:
		doc.append(env)
		doc.append(header)
		doc.append(f'#{"-"*63}\n\n')
	doc.append(f'{c}Title: {documentation.title}\n')
	doc.append(f'{c}Created at: {documentation.created_date}\n')
	doc.append(f'{c}Steps: {documentation.steps}\n\n')


	if steps:
		for step in steps:
			doc.append(f'{c}Step {step.position}: {step.description}')
			doc.append(f'{step.command}\n\n')
		file_content = ''.join(doc)

	else:
		if bash:
			doc.append('echo "No steps in this documentation"')
		else:
			doc.append('No steps in this documentation')
		file_content = ''.join(doc)

	with open(filename, 'w') as bashscript:
		bashscript.write(file_content)

	print(f'Documentation script available at: {filename}')
